$$a_{n} = a_{1} + (n - 1)\cdot d$$

In [4]:
suma = 200 + 24 -24 -24
print(suma)

176


In [ ]:
#1 y #2 
a = []
for i in range(36):
    n = i + 1
    a.append(24*n + 176)
print(f'El valor del termino que ocupa el lugar 36 en esta sucesion es: {a[i]}')

suma = sum(a)
print(f'La suma de los primeros 36 terminos es: {suma}')

El valor del termino que ocupa el lugar 36 en esta sucesion es: 1040
La suma de los primeros 36 terminos es: 22320


$$a_{n} = a_{1} \cdot r^{n-1}$$

In [ ]:
#4
g = []
for i in range(9):
    n = i + 1
    g.append(2000000 * 1.012**n)
print(f'El término 9 es: {g[i]:.0f}')


El término 9 es: 2226664


In [ ]:
#5 y #6

# a_n=a_1 * r**(n-1)

a_2 = 1066
a_5 = 8528


division = 8528/1066
print(division)
#Respuesta: 8

raiz = 8**(1/3)
print(raiz)
#Respuesta: 2

append = 1066/2
print(append)
#Respuesta: 533

8.0
2.0
533.0


In [ ]:
#5 y #6 parte 2
g = []
for i in range(9):
    n = i + 1
    g.append(533*2**(n-1))
print(f'El término 9 es: {g[i]:.0f}')

print(f'En el mes {g.index(34112)+1}')

El término 9 es: 136448
En el mes 7


$$a_{4} = a_{1} + (n - 1)\cdot d$$

In [ ]:
#7

a_4 = 1108000 # = #a_1 + 3d
                        # -
a_12 = 1396000 # = a_1 + 11d
                       # 8d


In [23]:
resta= 1396000 - 1108000
print(resta)
#Resultado: 288000

division = 288000/8
print(division)
#Resultado: 36000 = d

multiplicacion = 3 * 360000
print(multiplicacion)
#Resultado : 108000

resta= 1108000 - 108000
print(f'El valor de arriendo de un mes es {resta} $')

#1108000 = a_1 + 3 * 360000
#1108000 = a_1 + 108000
#a_1= 1000000

# an= 1000000 + (n-1)*36000

288000
36000.0
1080000
El valor de arriendo de un mes es 1000000 $


In [ ]:
#7 parte 2
a = []
for i in range(50):
    n = i + 1
    a.append(1000000 + (n-1)*36000)
print(f'En el mes {a.index(1828000)+1} tuvo un valor de 1828000 $')

En el mes 24 tuvo un valor de 1828000 $


In [ ]:
#8
import numpy as np

T = np.array([[300, 272, 240],
              [260, 180, 324]])

U = np.array([[1200, 1250],
              [1100, 1400],
              [1350, 1200]])

#Multiplicación de matrices
C = np.dot(T, U)
print(C)

#t22 = 965800


[[ 983200 1043800]
 [ 947400  965800]]


In [ ]:
#12
import numpy as np

S = np.array([[360, 280, 150, 420],
             [450, 370, 210, 130],
             [240, 260, 320, 340]])

C = np.array([[130, 310, 230, 280],
              [270, 240, 520, 370],
              [190, 290, 460, 410]])

t = 0.8*S + 1.1*C
print(f"{t}")


[[431. 565. 373. 644.]
 [657. 560. 740. 511.]
 [401. 527. 762. 723.]]


In [21]:
#13
A = np.fromfunction(lambda i, j: 2*(i+1)+3*(j+1), (3,3))
B = np.fromfunction(lambda i, j: 10*(i+1)*(j+1), (3,3))

C = A@B
print(C)

[[ 540. 1080. 1620.]
 [ 660. 1320. 1980.]
 [ 780. 1560. 2340.]]


In [28]:
#14
import numpy as np

A = np.array([[2,1],
              [3,-2]])

B = np.array([[10],
              [8]])

A_inv = np.linalg.inv(A)

X = A_inv@B
print(X)

[[4.]
 [2.]]


In [32]:
#15
import numpy as np

a = np.array([[2, 3],
              [1, 2]])

a_inv = np.linalg.inv(a)

#16
#print(a_inv)

#17
#print(a.T)

#19
suma = a + a.T
print(suma)

[[4 4]
 [4 4]]


In [ ]:
#20
import numpy as np

A = np.array([[2, 3],
              [1, 4]])

B = np.array([[52],
              [56]])

A_inv = np.linalg.inv(A)

X = A_inv@B
print(X)

[[ 8.]
 [12.]]
