In [ ]:
#3 

import numpy as np
from scipy.optimize import fsolve

def T(n):
    return 3*n + 5

print(T(101))

308


In [4]:
#5

x = np.array([5, 10, 15, 20])
y = np.array([200, 300, 400, 500])

pendiente, intercepto = np.polyfit(x, y, 1)

print(f'La funcion buscada es f(x) = {pendiente:.0f}x y {intercepto:.0f}')

La funcion buscada es f(x) = 20x y 100


In [5]:
#6

def U(t):
    return 1000*np.exp(0.1*t)

print(U(12))

3320.116922736548


In [7]:
#7

def D(t):
    return 2*1.2**t -20

xo = np.linspace(0,20,1)
solucion = fsolve(D, xo)

print(solucion)

[12.62925314]


In [10]:
#8

import numpy as np

sucesion = []
for i in range(36):
    n = i + 1
    sucesion.append(2.1 +(n-1)*0.1)
print(f'El término {n} es {sucesion[i]}')


El término 36 es 5.6


In [13]:
#9

sucesion = []
for i in range(5):
    n = i + 1
    sucesion.append(5*n**3 - 2*n)
print(f'El término {n} es {sucesion[i]}')

El término 5 es 615


In [14]:
#10

sucesion = []
for i in range(25):
    n = i + 1
    sucesion.append(1000 + (n-1)* 5)
print(f'El término {n} es {sucesion[i]}')

El término 25 es 1120


In [15]:
#11

import numpy as np

sucesion = []
for i in range(9):
    n = i + 1
    sucesion.append(3*2**(n-1))
print(f'El término {n} es {sucesion[i]}')

El término 9 es 768


In [21]:
#16

import numpy as np

A = np.array(([4, 6],
              [8, 5],
              [2, 7]))

B = np.array(([1, 7],
              [4, 6],
              [6, 5]))

C = 1.2*B
print(C)

#17

S = A + B
print(S)

[[1.2 8.4]
 [4.8 7.2]
 [7.2 6. ]]
[[ 5 13]
 [12 11]
 [ 8 12]]


In [24]:
#19

A = np.fromfunction(lambda i, j: 20*(i+1) * (j+1), (15,10))
E = np.fromfunction(lambda i, j: 4 *(i+1) + (j+1), (10,5))

M = A@E
print(M[7][2])

272800.0


In [25]:
#20

import numpy as np

A = np.array(([4, 8],
              [2, 6]))

B = np.array(([72],
              [40]))

A_inv = np.linalg.inv(A)

X = A_inv@B
print(X)

[[14.]
 [ 2.]]
